### ISSUE TITLE
TinyTranslations

### ISSUE THREAD

**Issue by CubBossa** [PQguanfang/UltimateShop#3]
Hey, are you generally interested in a PR that introduces support for the TinyTranslations framework?
https://www.spigotmc.org/resources/tinytranslations-translations-framework.113792/

**Comment by PQguanfang** [comment]
I'm sorry I didn't see your message before.

You can submit a new PR without interfering with the existing configuration, which means that old users can still use the old configuration, so you must make this a new feature and then add new options in the configuration file to enable or disable it, just like the current use-component option.

**Comment by CubBossa** [comment]
Would you want it to be a default feature? I mean its way more powerful than components and ampersand formatting. If not, would there be messages.yml and from TinyTranslations lang/en.properties?
